<?php

namespace Database\Seeders;

use App\Models\Tire;
use Illuminate\Database\Seeder;

class TireSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tires = [
            [
                'nama' => 'MICHELIN CITY GRIP 2 TL 110/70-12',
                'harga' => 582000,
                'stok' => 12,
                'gambar' => 'img/ban-motor/michelin-city-grip.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'Michelin',
                'ukuran_ban' => '110/70',
                'posisi_ban' => 'depan/belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 12',
                'tipe' => 'tubeless',
                'fitur' => 'Desain Pattern Modern, Kompon Karet Berkualitas Tinggi, Handling Stabil & Nyaman, Dirancang khusus untuk kebutuhan harian di area perkotaan',
                'deskripsi' => 'Ban Michelin City Grip 2 dirancang untuk memberikan grip maksimal pada permukaan basah maupun kering, meningkatkan keselamatan berkendara di perkotaan.',
            ],
            [
                'nama' => 'MICHELIN PILOT STREET 2 120/70-13',
                'harga' => 598000,
                'stok' => 10,
                'gambar' => 'img/ban-motor/michelin-pilot.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'Michelin',
                'ukuran_ban' => '120/70',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 13',
                'tipe' => 'tubeless',
                'fitur' => 'Handling Stabil & Nyaman, Kompon Karet Berkualitas Tinggi, Desain Pattern Modern',
                'deskripsi' => 'Ban motor sport touring premium dari Michelin yang menawarkan kestabilan tinggi pada kecepatan menengah hingga tinggi.',
            ],
            [
                'nama' => 'MICHELIN PILOT STREET 2 R 140/70-13',
                'harga' => 737000,
                'stok' => 8,
                'gambar' => 'img/ban-motor/michelin-pilot.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'Michelin',
                'ukuran_ban' => '140/70',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 13',
                'tipe' => 'tubeless',
                'fitur' => 'Kompon Karet Berkualitas Tinggi, Grip Maksimal, Tahan Lama',
                'deskripsi' => 'Pilihan ban belakang ideal untuk big matic Anda yang menginginkan performa premium di segala cuaca.',
            ],
            [
                'nama' => 'PLANETO Z TUBELESS 80/90-14',
                'harga' => 250000,
                'stok' => 25,
                'gambar' => 'img/ban-motor/planeto-z.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'planeto',
                'ukuran_ban' => '80/90',
                'posisi_ban' => 'depan',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Desain Pattern Modern, Harga Terjangkau, Tahan Lama',
                'deskripsi' => 'Ban Planeto Z menawarkan efisiensi bahan bakar yang baik dan kenyamanan berkendara harian dengan harga bersahabat.',
            ],
            [
                'nama' => 'PLANETO Z TUBELESS 90/90-14',
                'harga' => 285000,
                'stok' => 20,
                'gambar' => 'img/ban-motor/planeto-z.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'planeto',
                'ukuran_ban' => '90/90',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Desain Pattern Modern, Handling Stabil & Nyaman, Tahan Lama',
                'deskripsi' => 'Melengkapi kenyamanan perjalanan harian Anda dengan grip yang andal dan ban belakang yang awet.',
            ],
            [
                'nama' => 'DUNLOP TUBELESS SCOOTSMART-2 140/70-13',
                'harga' => 785000,
                'stok' => 15,
                'gambar' => 'img/ban-motor/dunlop-scootsmart.jpg',
                'jenis_ban' => 'ban motor big matic',
                'merek' => 'Dunlop',
                'ukuran_ban' => '140/70',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 13',
                'tipe' => 'tubeless',
                'fitur' => 'Desain Pattern Modern, Kompon Karet Berkualitas Tinggi, Handling Stabil & Nyaman',
                'deskripsi' => 'Ban premium dari Dunlop yang sangat cocok untuk skuter besar Anda, menghadirkan kenyamanan luar biasa saat berkendara jauh.',
            ],
            [
                'nama' => 'DUNLOP SPORTMAX Q-LITE 110/70-17',
                'harga' => 645000,
                'stok' => 14,
                'gambar' => 'img/ban-motor/dunlop-sportmax.jpg',
                'jenis_ban' => 'ban motor sport',
                'merek' => 'Dunlop',
                'ukuran_ban' => '110/70',
                'posisi_ban' => 'depan',
                'material' => 'medium compound',
                'diameter' => 'Ring 17',
                'tipe' => 'tubeless',
                'fitur' => 'Desain Pattern Modern, Kompon Karet Berkualitas Tinggi, Grip Maksimal',
                'deskripsi' => 'Dirancang untuk pengendara motor sport yang mendambakan grip agresif saat menikung dan berkendara kencang.',
            ],
            [
                'nama' => 'DUNLOP SPORTMAX Q-LITE 130/70-17',
                'harga' => 822000,
                'stok' => 10,
                'gambar' => 'img/ban-motor/dunlop-sportmax.jpg',
                'jenis_ban' => 'ban motor sport',
                'merek' => 'Dunlop',
                'ukuran_ban' => '130/70',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 17',
                'tipe' => 'tubeless',
                'fitur' => 'Handling Stabil & Nyaman, Grip Maksimal, Desain Pattern Modern',
                'deskripsi' => 'Ban belakang premium untuk kestabilan motor sport Anda, memberikan traksi maksimal di aspal kering maupun basah.',
            ],
            [
                'nama' => 'DUNLOP TUBELESS D115 90/90-14',
                'harga' => 342000,
                'stok' => 18,
                'gambar' => 'img/ban-motor/dunlop-d115.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'Dunlop',
                'ukuran_ban' => '90/90',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Desain Pattern Modern, Kompon Karet Berkualitas Tinggi, Handling Stabil & Nyaman, Dirancang khusus untuk kebutuhan harian di area perkotaan',
                'deskripsi' => 'Dunlop Tubeless D115 merupakan ban motor matic yang dirancang untuk memberikan keseimbangan antara kenyamanan, daya tahan, dan performa harian. Dengan desain tapak yang modern serta kompon karet berkualitas, ban ini mampu memberikan traksi optimal di berbagai kondisi jalan perkotaan.',
            ],
            [
                'nama' => 'ASPIRA MAXIO SPRINTER 70/90-17',
                'harga' => 180000,
                'stok' => 30,
                'gambar' => 'img/ban-motor/aspira-sprinter.jpg',
                'jenis_ban' => 'ban motor bebek',
                'merek' => 'aspira',
                'ukuran_ban' => '70/90',
                'posisi_ban' => 'depan',
                'material' => 'medium compound',
                'diameter' => 'Ring 17',
                'tipe' => 'tubetype',
                'fitur' => 'Desain Klasik Sporty, Kuat & Tahan Lama, Harga Sangat Terjangkau',
                'deskripsi' => 'Ban tipe tubetype dari Aspira yang sangat tangguh untuk melewati berbagai medan jalan di Indonesia, khusus motor bebek.',
            ],
            [
                'nama' => 'IRC ENZO TL 80/90-14',
                'harga' => 220000,
                'stok' => 20,
                'gambar' => 'img/ban-motor/irc-enzo.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'irc',
                'ukuran_ban' => '80/90',
                'posisi_ban' => 'depan',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Kompon Karet Berkualitas Tinggi, Grip Stabil, Awet',
                'deskripsi' => 'IRC Enzo menghadirkan cengkeraman berkendara sehari-hari dengan tapak ban yang awet dan traksi yang baik.',
            ],
            [
                'nama' => 'PIRELLI ANGEL SCOOTER 110/70-12',
                'harga' => 550000,
                'stok' => 12,
                'gambar' => 'img/ban-motor/pirelli-diablo.jpg',
                'jenis_ban' => 'ban motor big matic',
                'merek' => 'Pirelli',
                'ukuran_ban' => '110/70',
                'posisi_ban' => 'depan',
                'material' => 'medium compound',
                'diameter' => 'Ring 12',
                'tipe' => 'tubeless',
                'fitur' => 'Grip Maksimal di Basah, Kenyamanan Premium, Desain Sporty Pirelli',
                'deskripsi' => 'Rasakan sensasi berkendara kelas dunia dengan Pirelli Angel Scooter, menjamin traksi tinggi dan stabilitas di segala cuaca.',
            ],
            [
                'nama' => 'ECOSTREET TUBELESS 90/80-14',
                'harga' => 210000,
                'stok' => 22,
                'gambar' => 'img/ban-motor/ecostreet-tubeless.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'ecostreet',
                'ukuran_ban' => '90/80',
                'posisi_ban' => 'depan/belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Eco-Friendly, Tahan Lama, Desain Pattern Modern',
                'deskripsi' => 'Ban ramah lingkungan yang hemat bahan bakar dengan umur pakai yang sangat panjang.',
            ],
            [
                'nama' => 'PRESA PS-588 TUBELESS 100/80-14',
                'harga' => 310000,
                'stok' => 15,
                'gambar' => 'img/ban-motor/planeto-z.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'presa',
                'ukuran_ban' => '100/80',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Desain Pattern Modern, Grip Bagus, Tahan Panas',
                'deskripsi' => 'Ban Presa menawarkan grip tinggi dalam kondisi jalan panas berkat material compound khusus yang tahan panas.',
            ],
            [
                'nama' => 'SWALLOW PRO RACING 120/80-17',
                'harga' => 450000,
                'stok' => 10,
                'gambar' => 'img/ban-motor/pirelli-diablo.jpg',
                'jenis_ban' => 'ban motor sport',
                'merek' => 'swallow',
                'ukuran_ban' => '120/80',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 17',
                'tipe' => 'tubeless',
                'fitur' => 'Handling Stabil & Nyaman, Grip Agresif, Desain Sporty',
                'deskripsi' => 'Ban Swallow Pro Racing memberikan performa handling seperti di sirkuit untuk motor sport harian Anda.',
            ],
            [
                'nama' => 'KENDA K6022 100/90-12',
                'harga' => 290000,
                'stok' => 16,
                'gambar' => 'img/ban-motor/kenda.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'kenda',
                'ukuran_ban' => '100/90',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 12',
                'tipe' => 'tubeless',
                'fitur' => 'Cocok Cuaca Basah, Harga Bersahabat, Pola Tapak Menarik',
                'deskripsi' => 'Ban Kenda dengan pola tapak yang mampu membuang air dengan cepat, meminimalisir risiko aquaplaning.',
            ],
            [
                'nama' => 'FDR SPORT XR EVO 120/70-17',
                'harga' => 395000,
                'stok' => 19,
                'gambar' => 'img/ban-motor/fdr.jpg',
                'jenis_ban' => 'ban motor sport',
                'merek' => 'fdr',
                'ukuran_ban' => '120/70',
                'posisi_ban' => 'depan',
                'material' => 'medium compound',
                'diameter' => 'Ring 17',
                'tipe' => 'tubeless',
                'fitur' => 'Desain Pattern Modern, Grip Maksimal, Sangat Stabil',
                'deskripsi' => 'Ban FDR legendaris dengan teknologi kompon terbaik, memberikan performa handal untuk motor sport kesayangan.',
            ],
            [
                'nama' => 'ASPIRA PREMIO TERRENO 80/90-14',
                'harga' => 275000,
                'stok' => 14,
                'gambar' => 'img/ban-motor/aspira-premio-terreno.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'aspira',
                'ukuran_ban' => '80/90',
                'posisi_ban' => 'depan',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Ban Dual Purpose, Kuat di Segala Medan, Awet',
                'deskripsi' => 'Cocok untuk jalan aspal maupun jalanan berbatu halus, memberikan keandalan ekstra untuk petualangan harian.',
            ],
            [
                'nama' => 'PLANETO GOLD TUBELESS 90/80-14',
                'harga' => 320000,
                'stok' => 15,
                'gambar' => 'img/ban-motor/planeto-gold.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'planeto',
                'ukuran_ban' => '90/80',
                'posisi_ban' => 'depan/belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Desain Pattern Modern, Handling Stabil & Nyaman, Kompon Karet Premium',
                'deskripsi' => 'Planeto Gold menyajikan kenyamanan suspensi ekstra dan ketahanan gesekan tinggi di jalan aspal perkotaan.',
            ],
            [
                'nama' => 'IRC GP5 TUBELESS 100/90-14',
                'harga' => 335000,
                'stok' => 11,
                'gambar' => 'img/ban-motor/irc-gp5.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'irc',
                'ukuran_ban' => '100/90',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Dual Purpose Design, Awet, Grip Tangguh',
                'deskripsi' => 'Pola tapak kembangan yang dalam memberikan performa traksi unggulan saat musim hujan.',
            ],
            [
                'nama' => 'PIRELLI DIABLO ROSSO SPORT 90/80-17',
                'harga' => 495000,
                'stok' => 20,
                'gambar' => 'img/ban-motor/pirelli-diablo.jpg',
                'jenis_ban' => 'ban motor sport',
                'merek' => 'Pirelli',
                'ukuran_ban' => '90/80',
                'posisi_ban' => 'depan/belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 17',
                'tipe' => 'tubeless',
                'fitur' => 'Racing Look, Handling Maksimal, Grip Ekstra di Kering',
                'deskripsi' => 'Membawa DNA balap Pirelli ke aspal jalanan harian Anda. Sangat lincah dan memberikan grip luar biasa saat cornering.',
            ],
            [
                'nama' => 'SWALLOW SEAHORSE 80/80-14',
                'harga' => 195000,
                'stok' => 18,
                'gambar' => 'img/ban-motor/pirelli-diablo.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'swallow',
                'ukuran_ban' => '80/80',
                'posisi_ban' => 'depan',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Harga Ekonomis, Awet, Desain Pattern Unik',
                'deskripsi' => 'Menghadirkan efisiensi berkendara dengan harga ekonomis namun tetap mengutamakan aspek keselamatan mendasar.',
            ],
            [
                'nama' => 'FDR FLEMO TUBELESS 90/90-17',
                'harga' => 310000,
                'stok' => 12,
                'gambar' => 'img/ban-motor/fdr.jpg',
                'jenis_ban' => 'ban motor bebek',
                'merek' => 'fdr',
                'ukuran_ban' => '90/90',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 17',
                'tipe' => 'tubeless',
                'fitur' => 'Aman di Jalan Basah, Kembangan Indah, Tahan Gesekan',
                'deskripsi' => 'Ban bebek andalan FDR yang handal digunakan saat hujan lebat maupun jalanan terik kering.',
            ],
            [
                'nama' => 'KENDA DUAL SPORT K761 130/80-17',
                'harga' => 580000,
                'stok' => 8,
                'gambar' => 'img/ban-motor/kenda.jpg',
                'jenis_ban' => 'ban motor sport',
                'merek' => 'kenda',
                'ukuran_ban' => '130/80',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 17',
                'tipe' => 'tubeless',
                'fitur' => 'Offroad & Onroad Ready, Tangguh, Grip Kasar',
                'deskripsi' => 'Ban dual sport semi trail yang tangguh untuk motor sport adventure Anda melewati medan tanah dan aspal.',
            ],
            [
                'nama' => 'MICHELIN ANAKEE STREET 80/90-17',
                'harga' => 420000,
                'stok' => 15,
                'gambar' => 'img/ban-motor/michelin-anakee.jpg',
                'jenis_ban' => 'ban motor bebek',
                'merek' => 'Michelin',
                'ukuran_ban' => '80/90',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 17',
                'tipe' => 'tubeless',
                'fitur' => 'Kualitas Premium Michelin, Dual Purpose, Sangat Stabil',
                'deskripsi' => 'Perpaduan performa jalan raya dan jalan tanah dari Michelin untuk kenyamanan motor bebek harian.',
            ],
            [
                'nama' => 'PLANETO SPORT TUBELESS 110/80-14',
                'harga' => 395000,
                'stok' => 14,
                'gambar' => 'img/ban-motor/planeto-sport.jpg',
                'jenis_ban' => 'ban motor matic',
                'merek' => 'planeto',
                'ukuran_ban' => '110/80',
                'posisi_ban' => 'belakang',
                'material' => 'medium compound',
                'diameter' => 'Ring 14',
                'tipe' => 'tubeless',
                'fitur' => 'Kembangan Sporty, Grip Tangguh, Tahan Lama',
                'deskripsi' => 'Ban Planeto tipe sport dengan cengkeraman maksimal untuk motor matic berukuran sedang hingga besar.',
            ],
        ];

        foreach ($tires as $tire) {
            Tire::updateOrCreate(['nama' => $tire['nama']], $tire);
        }
    }
}
